# Generated by Django 3.0.6 on 2020-05-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_cargo', models.CharField(max_length=128, verbose_name='Descrição do cargo')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_hora', models.CharField(max_length=128, verbose_name='Descrição de configuração da hora')),
                ('hora_entrada_1', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 1')),
                ('hora_saida_1', models.TimeField(blank=True, null=True, verbose_name='Hora de saída 1')),
                ('hora_entrada_2', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 2')),
                ('hora_saida_2', models.TimeField(blank=True, null=True, verbose_name='Hora de saída 2')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_status', models.CharField(max_length=128, verbose_name='Descrição do status do ponto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoBatidaPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_ponto', models.CharField(max_length=128, verbose_name='Descrição da batida de ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do funcionário')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Cargo', verbose_name='Cargo do funcionário')),
                ('configuracao_hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.ConfiguracaoHora', verbose_name='Configuração da hora')),
                ('funcionario_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Funcionario')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ponto', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 1')),
                ('hora_saida_ponto', models.TimeField(blank=True, null=True, verbose_name='Hora da saida 1')),
                ('ip_registro', models.CharField(blank=True, default='192.168.0.104', editable=False, max_length=20, null=True)),
                ('data_resgistro', models.DateField(auto_now_add=True, null=True, verbose_name='Data do registro')),
                ('juntificativa', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Funcionario', verbose_name='Funcionário')),
                ('status_ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.StatusPonto', verbose_name='Status ponto')),
                ('tipo_ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.TipoBatidaPonto', verbose_name='Tipo ponto')),
            ],
        ),
    ]
