# Generated by Django 3.0.6 on 2020-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_s', '0002_auto_20200511_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='intervalo_inicial',
            field=models.TimeField(blank=True, null=True, verbose_name='Intervalo final'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='intervalo',
            field=models.TimeField(blank=True, null=True, verbose_name='Intervalo inicial'),
        ),
    ]
